/**
 * Build-time catalog generator: Coolify's OpenAPI spec -> src/generated/*.
 *
 * Run with `npm run codegen`. The catalog is committed rather than fetched at
 * runtime because every MCP client spawns this process fresh: a 795 KB parse
 * per start, a network dependency for a tool that often runs against an offline
 * homelab, and a non-deterministic npm tarball are each worse than a file in
 * git. CI re-runs this and diffs the result, so upstream drift breaks the build
 * loudly instead of shipping a stale surface silently.
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type {
  CatalogMeta,
  CatalogOperation,
  DangerClass,
  HttpMethod,
  OperationFamily,
} from '../src/types.js';

// ---------------------------------------------------------------------------
// Pinned expectations — the tripwires
// ---------------------------------------------------------------------------

/**
 * Operations in the vendored spec. Asserted, not measured: a generator that
 * quietly adapts to whatever it is fed will happily emit a half-catalog after a
 * bad spec refresh. Bump this deliberately, in the same commit as the new spec.
 */
const EXPECTED_RAW_OPERATIONS = 189;

/**
 * The spec's own `info.version` is the constant "0.1" and carries no
 * information. This is the coollabsio/coolify release the spec was taken from.
 */
const COOLIFY_VERSION = '4.2.0';

/**
 * Hand-maintained. These are not DELETEs, so the "gate the DELETEs" rule misses
 * them, yet they switch the API off — from the token's own point of view that
 * is irreversible, because the call that would switch it back on is itself
 * behind the API that just went away.
 *
 * Keyed by route rather than operationId: the route is the semantic identity,
 * while the id is generated by upstream tooling and can be renamed. Every entry
 * must match exactly one operation or the generator fails.
 */
const DESTRUCTIVE_OVERRIDE_ROUTES: readonly string[] = ['POST /disable', 'POST /mcp/disable'];

/**
 * Provisions billable cloud infrastructure. Not gated — the brief keeps
 * everything non-destructive open — but surfaced in search results so the model
 * sees the consequence before it calls.
 */
const COSTLY_ROUTES: readonly string[] = [
  'POST /servers/hetzner',
  'POST /servers/digitalocean',
  'POST /servers/vultr',
];

// ---------------------------------------------------------------------------
// Stub stripping
// ---------------------------------------------------------------------------

/**
 * Coolify registers GET routes that reach `OtherController@post_required` and
 * return nothing but "use POST". If one enters the catalog, a search for
 * "restart application" returns a GET — which the tool layer is entitled to
 * annotate `readOnlyHint: true` — that actually restarts the application.
 *
 * Detected by pattern, never by a hardcoded path list, so the defence survives
 * upstream adding or moving such routes.
 */
const POST_REQUIRED_TEXT = /post_required/i;

/**
 * Last path segments that name a state change. A GET here is a stub by
 * construction: Coolify exposes none of these as readable resources, so there
 * is no legitimate operation to lose.
 */
const ACTION_SEGMENTS: ReadonlySet<string> = new Set([
  'start',
  'stop',
  'restart',
  'deploy',
  'enable',
  'disable',
  'validate',
  'cancel',
]);

// ---------------------------------------------------------------------------
// Families
// ---------------------------------------------------------------------------

/**
 * First non-parameter path segment -> family. Segments absent here fall back to
 * `other`; that is deliberate rather than fatal, because the raw-count assertion
 * already forces a human to look whenever upstream adds routes.
 */
const FAMILY_BY_SEGMENT: Readonly<Record<string, OperationFamily>> = {
  applications: 'applications',
  databases: 'databases',
  services: 'services',
  servers: 'servers',
  projects: 'projects',
  deployments: 'deployments',
  // POST /deploy triggers a deployment; filing it anywhere else splits the one
  // concept a user searches for across two families.
  deploy: 'deployments',
  teams: 'teams',
  security: 'security',
  destinations: 'destinations',
  'github-apps': 'github-apps',
  'cloud-tokens': 'cloud-tokens',
  hetzner: 'hetzner',
  digitalocean: 'digitalocean',
  vultr: 'vultr',
  tags: 'tags',
};

// ---------------------------------------------------------------------------
// Schema pruning
// ---------------------------------------------------------------------------

/** Descriptions longer than this are dropped whole. Context budget beats prose. */
const MAX_DESCRIPTION_CHARS = 200;

/** Summaries are search text and are shown per result row; keep them one line. */
const MAX_SUMMARY_CHARS = 160;

/**
 * Keys copied verbatim. An allowlist, not a denylist: a denylist silently leaks
 * whatever OpenAPI adds next, and the whole point of this pass is a bounded
 * payload. Includes vocabulary the current spec does not use yet, so a future
 * upstream constraint is preserved rather than dropped.
 */
const SCALAR_SCHEMA_KEYS: ReadonlySet<string> = new Set([
  'type',
  'format',
  'title',
  'description',
  'required',
  'nullable',
  'deprecated',
  'readOnly',
  'writeOnly',
  'minimum',
  'maximum',
  'exclusiveMinimum',
  'exclusiveMaximum',
  'multipleOf',
  'minLength',
  'maxLength',
  'pattern',
  'minItems',
  'maxItems',
  'uniqueItems',
  'minProperties',
  'maxProperties',
]);

/** Keys whose value is itself a schema (or an array of schemas). */
const NESTED_SCHEMA_KEYS: ReadonlySet<string> = new Set([
  'items',
  'additionalProperties',
  'not',
  'oneOf',
  'anyOf',
  'allOf',
]);

/** Keys whose value is a map of property name -> schema. */
const SCHEMA_MAP_KEYS: ReadonlySet<string> = new Set(['properties', 'patternProperties']);

/**
 * Keys holding instance data rather than schemas. Copied untouched — running the
 * key allowlist over a `default: { ... }` value would mangle real data.
 */
const OPAQUE_SCHEMA_KEYS: ReadonlySet<string> = new Set(['default', 'const', 'enum']);

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const SCRIPT_DIR = fileURLToPath(new URL('.', import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, '..');
const SPEC_PATH = join(SCRIPT_DIR, 'coolify-openapi.json');
const OUT_DIR = join(REPO_ROOT, 'src', 'generated');

const BANNER = [
  '// GENERATED FILE — DO NOT EDIT, run npm run codegen',
  `// Source: scripts/coolify-openapi.json (Coolify ${COOLIFY_VERSION})`,
  '',
].join('\n');

const METHOD_ORDER: readonly HttpMethod[] = ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'];

// ---------------------------------------------------------------------------
// Minimal spec shape — only the parts this generator reads
// ---------------------------------------------------------------------------

interface OpenApiParameter {
  name?: string;
  in?: string;
}

interface OpenApiOperation {
  operationId?: string;
  summary?: string;
  description?: string;
  parameters?: OpenApiParameter[];
  requestBody?: { content?: Record<string, { schema?: unknown } | undefined> };
  responses?: Record<string, unknown>;
}

interface OpenApiSpec {
  paths?: Record<string, Record<string, OpenApiOperation> | undefined>;
  components?: Record<string, unknown>;
}

interface RawOperation {
  id: string;
  method: HttpMethod;
  path: string;
  route: string;
  op: OpenApiOperation;
}

function fail(message: string): never {
  process.stderr.write(`\ncodegen FAILED: ${message}\n\n`);
  process.exit(1);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

// ---------------------------------------------------------------------------
// Collection
// ---------------------------------------------------------------------------

function collectRawOperations(spec: OpenApiSpec): RawOperation[] {
  const collected: RawOperation[] = [];
  for (const [path, item] of Object.entries(spec.paths ?? {})) {
    for (const [verb, op] of Object.entries(item ?? {})) {
      const method = METHOD_ORDER.find((m) => m === verb.toUpperCase());
      if (method === undefined) continue;
      const id = op.operationId?.trim();
      if (!id) fail(`${verb.toUpperCase()} ${path} has no operationId — it cannot be addressed.`);
      collected.push({ id, method, path, route: `${method} ${path}`, op });
    }
  }
  return collected;
}

/** Returns why this operation is a stub, or undefined when it is real. */
function stubReason(raw: RawOperation): string | undefined {
  const text = `${raw.op.summary ?? ''} ${raw.op.description ?? ''} ${raw.id}`;
  if (POST_REQUIRED_TEXT.test(text)) return 'post_required text';

  const codes = Object.keys(raw.op.responses ?? {});
  const hasSuccess = codes.some((code) => /^[23]\d\d$/.test(code) || code === 'default');
  if (!hasSuccess) return `no success response (${codes.join(',') || 'none'})`;

  // A GET that Coolify answers with "use POST" may still document a 200 for the
  // error envelope, so the response check alone is not enough.
  const segments = raw.path.split('/').filter(Boolean);
  const last = segments[segments.length - 1];
  if (raw.method === 'GET' && last !== undefined && ACTION_SEGMENTS.has(last)) {
    return `GET on action route /${last}`;
  }
  return undefined;
}

// ---------------------------------------------------------------------------
// Classification
// ---------------------------------------------------------------------------

function classifyDanger(raw: RawOperation, overrides: ReadonlySet<string>): DangerClass {
  if (raw.method === 'DELETE' || overrides.has(raw.route)) return 'destructive';
  if (raw.method === 'GET') return 'safe';
  return 'write';
}

function familyFor(path: string): OperationFamily {
  const segment = path.split('/').find((s) => s.length > 0 && !s.startsWith('{'));
  if (segment === undefined) return 'other';
  return FAMILY_BY_SEGMENT[segment] ?? 'other';
}

function firstSentence(text: string): string {
  const match = /^[\s\S]*?[.!?](?=\s|$)/.exec(text.trim());
  return (match?.[0] ?? text).trim();
}

function truncate(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, max - 1).trimEnd()}…`;
}

/**
 * The spec's `summary` is a UI label — "List", "Get", "Start" — which is close
 * to worthless as search text once it is separated from the sidebar heading it
 * was written under. `description` is the sentence that actually names the
 * resource, so it wins.
 */
function summaryFor(raw: RawOperation): string {
  const description = firstSentence(raw.op.description ?? '');
  const summary = (raw.op.summary ?? '').trim();
  return truncate(description || summary || raw.id, MAX_SUMMARY_CHARS);
}

function pathParamsOf(path: string): string[] {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1] ?? '');
}

function queryParamsOf(raw: RawOperation): string[] {
  const names: string[] = [];
  for (const parameter of raw.op.parameters ?? []) {
    const { name } = parameter;
    if (parameter.in === 'query' && typeof name === 'string' && name.length > 0) names.push(name);
  }
  return names;
}

function toCatalogOperation(
  raw: RawOperation,
  overrides: ReadonlySet<string>,
  costly: ReadonlySet<string>,
): CatalogOperation {
  const row: CatalogOperation = {
    id: raw.id,
    method: raw.method,
    path: raw.path,
    family: familyFor(raw.path),
    summary: summaryFor(raw),
    // Taken from the URL template, not from `parameters`: the template is what
    // the HTTP client must actually substitute, and specs under-declare.
    pathParams: pathParamsOf(raw.path),
    queryParams: queryParamsOf(raw),
    // Derived from the same lookup that emits the schema, so `hasBody === true`
    // and "getSchema(id) returns something" can never disagree.
    hasBody: bodySchemaOf(raw) !== undefined,
    danger: classifyDanger(raw, overrides),
  };
  if (costly.has(raw.route)) row.costly = true;
  return row;
}

// ---------------------------------------------------------------------------
// Request body schemas
// ---------------------------------------------------------------------------

function bodySchemaOf(raw: RawOperation): unknown {
  return raw.op.requestBody?.content?.['application/json']?.schema;
}

function resolveRef(spec: OpenApiSpec, ref: string): unknown {
  if (!ref.startsWith('#/')) fail(`external $ref is not supported: ${ref}`);
  let node: unknown = spec;
  for (const segment of ref.slice(2).split('/')) {
    if (!isRecord(node)) fail(`unresolvable $ref: ${ref}`);
    node = node[segment.replace(/~1/g, '/').replace(/~0/g, '~')];
  }
  if (node === undefined) fail(`unresolvable $ref: ${ref}`);
  return node;
}

function dereference(node: unknown, spec: OpenApiSpec, seen: ReadonlySet<string>): unknown {
  if (Array.isArray(node)) return node.map((child) => dereference(child, spec, seen));
  if (!isRecord(node)) return node;

  const ref = node['$ref'];
  if (typeof ref === 'string') {
    // A self-referential schema cannot be inlined. `type: object` is a truthful
    // stand-in here because the generic execute path passes bodies through
    // without validating them anyway.
    if (seen.has(ref)) return { type: 'object' };
    return dereference(resolveRef(spec, ref), spec, new Set([...seen, ref]));
  }

  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) out[key] = dereference(value, spec, seen);
  return out;
}

function pruneSchema(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(pruneSchema);
  if (!isRecord(node)) return node;

  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) {
    if (SCHEMA_MAP_KEYS.has(key)) {
      out[key] = pruneSchemaMap(value);
    } else if (NESTED_SCHEMA_KEYS.has(key)) {
      out[key] = pruneSchema(value);
    } else if (OPAQUE_SCHEMA_KEYS.has(key)) {
      out[key] = value;
    } else if (key === 'description') {
      if (typeof value === 'string' && value.length <= MAX_DESCRIPTION_CHARS) out[key] = value;
    } else if (SCALAR_SCHEMA_KEYS.has(key)) {
      out[key] = value;
    }
    // Everything else — `example`, `examples`, vendor extensions — is dropped.
  }
  return out;
}

/** Property names are data, so only the values run through the key allowlist. */
function pruneSchemaMap(node: unknown): unknown {
  if (!isRecord(node)) return pruneSchema(node);
  const out: Record<string, unknown> = {};
  for (const [name, schema] of Object.entries(node)) out[name] = pruneSchema(schema);
  return out;
}

function buildSchemas(spec: OpenApiSpec, kept: readonly RawOperation[]): Record<string, unknown> {
  const schemas: Record<string, unknown> = {};
  for (const raw of kept) {
    const schema = bodySchemaOf(raw);
    if (schema === undefined) continue;
    schemas[raw.id] = pruneSchema(dereference(schema, spec, new Set()));
  }
  return schemas;
}

// ---------------------------------------------------------------------------
// Rendering — output is prettier-shaped so `format:check` stays green
// ---------------------------------------------------------------------------

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Column budget for keeping an array on one line. Matches prettier's default. */
const INLINE_WIDTH = 72;

function renderString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
  return `'${escaped}'`;
}

/**
 * Objects always expand and arrays collapse when they fit. That is prettier's
 * own shape, which keeps `format:check` from fighting the generator, and it
 * happens to be the readable choice: one field per line diffs cleanly, while
 * `pathParams: ['uuid']` on its own three lines would not.
 */
function renderValue(value: unknown, indent: string): string {
  if (typeof value === 'string') return renderString(value);
  if (typeof value === 'number' || typeof value === 'boolean' || value === null) {
    return String(value);
  }

  const inner = `${indent}  `;
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const parts = value.map((item) => renderValue(item, inner));
    const inline = `[${parts.join(', ')}]`;
    if (!inline.includes('\n') && indent.length + inline.length <= INLINE_WIDTH) return inline;
    return `[\n${parts.map((part) => `${inner}${part},`).join('\n')}\n${indent}]`;
  }

  if (isRecord(value)) {
    const entries = Object.entries(value).filter(([, v]) => v !== undefined);
    if (entries.length === 0) return '{}';
    const lines = entries.map(([key, v]) => {
      const renderedKey = IDENTIFIER.test(key) ? key : renderString(key);
      return `${inner}${renderedKey}: ${renderValue(v, inner)},`;
    });
    return `{\n${lines.join('\n')}\n${indent}}`;
  }

  return 'null';
}

function renderCatalog(rows: readonly CatalogOperation[]): string {
  return [
    BANNER,
    "import type { CatalogOperation } from '../types.js';",
    '',
    `export const CATALOG: CatalogOperation[] = ${renderValue(rows, '')};`,
    '',
  ].join('\n');
}

function renderSchemas(schemas: Record<string, unknown>): string {
  return [
    BANNER,
    '/**',
    ' * Dereferenced, pruned request-body schemas keyed by operation id.',
    ' * Absent id means the operation takes no JSON body.',
    ' */',
    `export const SCHEMAS: Record<string, unknown> = ${renderValue(schemas, '')};`,
    '',
  ].join('\n');
}

function renderMeta(meta: CatalogMeta): string {
  return [
    BANNER,
    "import type { CatalogMeta } from '../types.js';",
    '',
    `export const METADATA: CatalogMeta = ${renderValue(meta, '')};`,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Deterministic timestamp
// ---------------------------------------------------------------------------

const GENERATED_AT_PLACEHOLDER = '__GENERATED_AT__';

function readIfExists(path: string): string | undefined {
  return existsSync(path) ? readFileSync(path, 'utf8') : undefined;
}

/** Git may have handed us CRLF on checkout; that is not a content change. */
function sameContent(a: string | undefined, b: string): boolean {
  return a !== undefined && a.replace(/\r\n/g, '\n') === b.replace(/\r\n/g, '\n');
}

/**
 * `generatedAt` would otherwise dirty the tree on every run, and CI runs
 * `npm run codegen && git diff --exit-code`. So the stamp only moves when the
 * emitted content moves: re-running against an unchanged spec is a no-op.
 */
function resolveGeneratedAt(previousMeta: string | undefined, template: string): string {
  const now = new Date().toISOString();
  if (previousMeta === undefined) return now;
  const previousStamp = /generatedAt: '([^']*)'/.exec(previousMeta)?.[1];
  if (previousStamp === undefined) return now;
  const replayed = template.replace(
    renderString(GENERATED_AT_PLACEHOLDER),
    renderString(previousStamp),
  );
  return sameContent(previousMeta, replayed) ? previousStamp : now;
}

// ---------------------------------------------------------------------------
// Assertions
// ---------------------------------------------------------------------------

function assertRoutesMatched(
  label: string,
  declared: readonly string[],
  present: ReadonlySet<string>,
): void {
  const missing = declared.filter((route) => !present.has(route));
  if (missing.length > 0) {
    fail(
      `${label} lists ${missing.length} route(s) that no longer exist: ${missing.join(', ')}.\n` +
        'Either upstream moved them or the spec is wrong. Do not delete the entry to make ' +
        'this pass — find where the operation went first.',
    );
  }
}

function syntheticOperation(method: HttpMethod, path: string, op: OpenApiOperation): RawOperation {
  return { id: 'synthetic', method, path, route: `${method} ${path}`, op };
}

/**
 * The stub detector strips nothing from the current spec — this revision simply
 * does not document the `post_required` GETs. That leaves the single most
 * safety-critical rule in this generator as unexercised code, free to rot until
 * an upstream release brings the stubs back and a GET that restarts an
 * application lands in a tool annotated `readOnlyHint: true`. So it is proved
 * against synthetic stubs on every run, one case per rule, plus a control that
 * must survive.
 */
function assertStubDetectorWorks(): void {
  const stubs: ReadonlyArray<readonly [string, RawOperation]> = [
    [
      'GET on an action route that documents a 200',
      syntheticOperation('GET', '/applications/{uuid}/restart', {
        summary: 'Restart',
        responses: { '200': {} },
      }),
    ],
    [
      'operation with no success response',
      syntheticOperation('GET', '/servers/{uuid}/anything', {
        responses: { '404': {}, '405': {} },
      }),
    ],
    [
      'operation whose description names post_required',
      syntheticOperation('GET', '/servers/{uuid}/anything', {
        description: 'See OtherController@post_required.',
        responses: { '200': {} },
      }),
    ],
  ];
  for (const [label, raw] of stubs) {
    if (stubReason(raw) === undefined) {
      fail(`the post_required stub detector no longer catches: ${label}`);
    }
  }

  const real = syntheticOperation('GET', '/applications', {
    summary: 'List',
    responses: { '200': {}, '401': {} },
  });
  const reason = stubReason(real);
  if (reason !== undefined) fail(`the stub detector strips real operations: ${reason}`);
}

function assertCatalogInvariants(rows: readonly CatalogOperation[]): void {
  const seen = new Set<string>();
  for (const row of rows) {
    if (seen.has(row.id)) fail(`duplicate operation id: ${row.id}`);
    seen.add(row.id);
    if (row.danger === 'safe' && row.method !== 'GET') {
      fail(`${row.id} is classified safe but is a ${row.method}`);
    }
    if (row.danger === 'destructive' && row.method === 'GET') {
      fail(`${row.id} is classified destructive but is a GET`);
    }
  }
  if (rows.length === 0) fail('catalog is empty');
}

function assertSchemaCoverage(
  rows: readonly CatalogOperation[],
  schemas: Record<string, unknown>,
): void {
  const withBody = new Set(rows.filter((r) => r.hasBody).map((r) => r.id));
  const emitted = new Set(Object.keys(schemas));
  const missing = [...withBody].filter((id) => !emitted.has(id));
  const extra = [...emitted].filter((id) => !withBody.has(id));
  if (missing.length > 0) fail(`hasBody without a schema: ${missing.join(', ')}`);
  if (extra.length > 0) fail(`schema without a catalog row: ${extra.join(', ')}`);
}

// ---------------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------------

function printTable(title: string, rows: ReadonlyArray<readonly [string, string]>): void {
  const width = Math.max(...rows.map(([label]) => label.length));
  const lines = rows.map(([label, value]) => `  ${label.padEnd(width)}  ${value}`);
  process.stdout.write(`\n${title}\n${lines.join('\n')}\n`);
}

function countBy<T extends string>(values: readonly T[]): Array<readonly [string, string]> {
  const counts = new Map<string, number>();
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1);
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([key, count]) => [key, String(count)] as const);
}

function reportUnmappedSegments(rows: readonly CatalogOperation[]): void {
  const unmapped = new Set(
    rows
      .filter((r) => r.family === 'other')
      .map((r) => r.path.split('/').filter(Boolean)[0] ?? '/'),
  );
  if (unmapped.size === 0) return;
  process.stdout.write(
    `\n  note: filed under 'other' — ${[...unmapped].sort().join(', ')}\n` +
      '        add a FAMILY_BY_SEGMENT entry if any of these deserve their own family.\n',
  );
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const specSource = readFileSync(SPEC_PATH, 'utf8');
  const specSha256 = createHash('sha256').update(specSource).digest('hex');
  const spec = JSON.parse(specSource) as OpenApiSpec;

  const rawOperations = collectRawOperations(spec);
  if (rawOperations.length !== EXPECTED_RAW_OPERATIONS) {
    fail(
      `expected ${EXPECTED_RAW_OPERATIONS} operations in the spec, found ${rawOperations.length}.\n` +
        'The vendored spec changed. Review the diff, then update EXPECTED_RAW_OPERATIONS in the ' +
        'same commit — never adjust it to silence this.',
    );
  }

  const routes = new Set(rawOperations.map((raw) => raw.route));
  assertRoutesMatched('DESTRUCTIVE_OVERRIDE_ROUTES', DESTRUCTIVE_OVERRIDE_ROUTES, routes);
  assertRoutesMatched('COSTLY_ROUTES', COSTLY_ROUTES, routes);
  assertStubDetectorWorks();

  const stripped: Array<readonly [string, string]> = [];
  const kept: RawOperation[] = [];
  for (const raw of rawOperations) {
    const reason = stubReason(raw);
    if (reason === undefined) kept.push(raw);
    else stripped.push([raw.route, reason] as const);
  }

  const overrides = new Set(DESTRUCTIVE_OVERRIDE_ROUTES);
  const costly = new Set(COSTLY_ROUTES);
  const rows = kept
    .map((raw) => toCatalogOperation(raw, overrides, costly))
    .sort(
      (a, b) =>
        a.family.localeCompare(b.family) ||
        a.path.localeCompare(b.path) ||
        METHOD_ORDER.indexOf(a.method) - METHOD_ORDER.indexOf(b.method) ||
        a.id.localeCompare(b.id),
    );

  assertCatalogInvariants(rows);
  const schemas = buildSchemas(spec, kept);
  assertSchemaCoverage(rows, schemas);

  const catalogSource = renderCatalog(rows);
  const schemasSource = renderSchemas(schemas);
  const metaTemplate = renderMeta({
    coolifyVersion: COOLIFY_VERSION,
    specSha256,
    rawOperationCount: rawOperations.length,
    strippedCount: stripped.length,
    operationCount: rows.length,
    generatedAt: GENERATED_AT_PLACEHOLDER,
  });

  const catalogPath = join(OUT_DIR, 'catalog.ts');
  const schemasPath = join(OUT_DIR, 'schemas.ts');
  const metaPath = join(OUT_DIR, 'meta.ts');

  const unchangedElsewhere =
    sameContent(readIfExists(catalogPath), catalogSource) &&
    sameContent(readIfExists(schemasPath), schemasSource);
  const generatedAt = unchangedElsewhere
    ? resolveGeneratedAt(readIfExists(metaPath), metaTemplate)
    : new Date().toISOString();
  const metaSource = metaTemplate.replace(
    renderString(GENERATED_AT_PLACEHOLDER),
    renderString(generatedAt),
  );

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(catalogPath, catalogSource, 'utf8');
  writeFileSync(schemasPath, schemasSource, 'utf8');
  writeFileSync(metaPath, metaSource, 'utf8');

  printTable('coolify-mcp catalog', [
    ['coolify version', COOLIFY_VERSION],
    ['spec sha256', `${specSha256.slice(0, 16)}…`],
    ['raw operations', String(rawOperations.length)],
    ['stripped stubs', String(stripped.length)],
    ['catalog operations', String(rows.length)],
    ['body schemas', String(Object.keys(schemas).length)],
    ['generated at', generatedAt],
  ]);
  printTable('by danger', countBy(rows.map((r) => r.danger)));
  printTable('by method', countBy(rows.map((r) => r.method)));
  printTable('by family', countBy(rows.map((r) => r.family)));
  if (stripped.length > 0) printTable('stripped', stripped);
  reportUnmappedSegments(rows);
  process.stdout.write(`\nwrote ${catalogPath}\n      ${schemasPath}\n      ${metaPath}\n\n`);
}

main();
